---
title: "cleaning_file"
author: "Taylor Franklin"
date: "12/15/2020"
output: html_document
---

```{r}
#import libraries
library(tidyverse)
library(censusapi)
```
```{r}
#census key is saved as text file in the data folder
key = read_lines('data/census_api_key.txt')
```

```{r}
# Add key to .Renviron
Sys.setenv(CENSUS_KEY=key)

# Check to see that the expected key is output in your R console
Sys.getenv("CENSUS_KEY")
```

```{r}
#get ACS1 variables
acs1vars <- listCensusMetadata(
    name = "acs/acs1", 
    type = "variables",
    vintage = 2019)
```

```{r}
#get race related variables
race <- getCensus(
   name = "acs/acs1",
   vintage = 2019,
   vars = 'group(B02001)',
   region = 'metropolitan statistical area/micropolitan statistical area:34980, 16860, 28940, 32820')
```

```{r}
#storing all columns from race
race_colnames <- colnames(race)
```

```{r}
#storing columns related to race
race_vars <- colnames(race)[2:41]
```


```{r}
#storing labels from metadata related to race
race_labels <- acs1vars %>%
   filter(name %in% race_vars) %>%
   select(label) %>%
   pull()
```

```{r}
#naming elements of the race labels vector
names(race_labels) <- acs1vars %>%
   filter(name %in% race_vars) %>%
   select(name) %>%
   pull() 
```

```{r}
#renaming columns using named vector
colnames(race) <- c(colnames(race)[1], race_labels[race_colnames[2:41]], colnames(race[42:43]))
```

```{r}
#remove columns that have all null values
race <- race[colSums(!is.na(race)) > 0]
```

```{r}
#rename null columns by index
race <- rename(race, drop_me = c(3, 5, 7, 9, 11, 13, 15, 17, 19, 21))
```

```{r}
#drop unnecessary columns
race <- race %>% 
   select(-metropolitan_statistical_area_micropolitan_statistical_area, -GEO_ID, -starts_with('drop_me'))
```

```{r}
#remove excess string from columns
colnames(race) <- str_remove_all(colnames(race), 'Estimate!!Total:!!')
colnames(race) <- str_remove_all(colnames(race), 'Two or more races:!!')
colnames(race) <- str_remove_all(colnames(race), 'alone')
colnames(race) <- str_remove_all(colnames(race), ':')

#trim white space
colnames(race) <- str_trim(colnames(race), side = 'right')
```

```{r}
#rename columns
race <- rename(race, Total = `Estimate!!Total`)
race <- rename(race, metro_area = NAME)
race <- rename(race, Black = `Black or African American`)
race <- rename(race, AIAN = `American Indian and Alaska Native`)
race <- rename(race, NHPI = `Native Hawaiian and Other Pacific Islander`)
race <- rename(race, Other = `Some other race`)
race <- rename(race, Multiple = `Two or more races`)
```

```{r}
#removing more columns
race <- race %>% 
  select(-starts_with('Two races'))
```

```{r}
#pivot data
race <- race %>% 
   pivot_longer(cols = c(Total, White, Black, Asian, AIAN, NHPI, Other, Multiple), names_to = 'race', values_to = 'estimate')
```

```{r}
#save race to csv file
write_csv(race, 'data/race.csv')
```

#doing the same steps as above but for sex by age from ACS1
```{r}
#getting sex by age from Census API
sex_by_age <- getCensus(
   name = "acs/acs1",
   vintage = 2019,
   vars = 'group(B01001)',
   region = 'metropolitan statistical area/micropolitan statistical area:34980, 16860, 28940, 32820')
```

```{r}
#getting all column names
sex_by_age_colnames <- colnames(sex_by_age)
```

```{r}
#isolating needed columns
sex_by_age_vars <- sex_by_age_colnames[2:199]
```

```{r}
#getting labels from metadata that match sba columns 
sex_by_age_labels <- acs1vars %>%
   filter(name %in% sex_by_age_vars) %>%
   select(label) %>%
   pull()
```

```{r}
#naming elements of the vector
names(sex_by_age_labels) <- acs1vars %>%
   filter(name %in% sex_by_age_vars) %>%
   select(name) %>%
   pull() 
```


```{r}
#renaming columns using named vector
colnames(sex_by_age) <- c(colnames(sex_by_age)[1], sex_by_age_labels[sex_by_age_colnames[2:199]])
```

```{r}
#remove columns that have all null values
sex_by_age <- sex_by_age[colSums(!is.na(sex_by_age)) > 0]
```

```{r}
#turning into tibble to use name_repair and access null column names
sex_by_age <- as_tibble(sex_by_age, .name_repair = 'unique')
```
```{r}
#renaming NAME column to metro_area
sex_by_age <- rename(sex_by_age, metro_area = 101)
```

```{r}
#removing null columns
sex_by_age<- sex_by_age %>% 
   select(-starts_with('.'), -starts_with('NA'), -metropolitan_statistical_area_micropolitan_statistical_area, -Geography)
```

```{r}
#remove excess !! from columns
colnames(sex_by_age) <- str_remove_all(colnames(sex_by_age), '!!')
colnames(sex_by_age) <- str_remove_all(colnames(sex_by_age), ':')
colnames(sex_by_age) <- str_remove_all(colnames(sex_by_age), 'EstimateTotal')

#rename total population column by index
sex_by_age <- rename(sex_by_age, Total = 1)
```

```{r}
#create males 
males <- sex_by_age %>% 
   select(metro_area, starts_with('Male')) 

#create females
females <- sex_by_age %>% 
   select(metro_area, starts_with('Female'))
```

```{r}
#removing Male from column names
colnames(males) <- colnames(males) %>% 
   str_replace('Male', '')

#creating sex column
males$sex <- c('Male')

#removing total column
males <- males %>% 
   select(-2)
```

```{r}
#removing Female from column names
colnames(females) <- colnames(females) %>% 
   str_replace('Female', '')

#creating sex column
females$sex <- c('Female')

#removing total column
females <- females %>% 
   select(-2)
```

```{r}
#combining age group columns
males <- males %>% 
   mutate(
      `Under 20` = (`Under 5 years` + `5 to 9 years` + `10 to 14 years` + `15 to 17 years` + `18 and 19 years` + `20 years`),
      `20 to 29` = (`21 years` + `22 to 24 years` + `25 to 29 years`),
      `30 to 39` = (`30 to 34 years` + `35 to 39 years`),
      `40 to 49` = (`40 to 44 years` + `45 to 49 years`),
      `50 to 59` = (`50 to 54 years` + `55 to 59 years`),
      `60 and over` = (`60 and 61 years` + `62 to 64 years` + `65 and 66 years` + `67 to 69 years` + `70 to 74 years` + `75 to 79 years` + `80 to 84 years` + `85 years and over`)
         ) %>% 
   select(metro_area, sex, `20 to 29`, `30 to 39`, `40 to 49`, `50 to 59`, `60 and over`) 
```

```{r}
#pivoting
males <- males %>% 
pivot_longer(cols = colnames(males)[3:7], names_to = 'age', values_to = 'estimate')
```

```{r}
#combining age columns
females <- females %>% 
   mutate(
      `Under 20` = (`Under 5 years` + `5 to 9 years` + `10 to 14 years` + `15 to 17 years` + `18 and 19 years` + `20 years`),
      `20 to 29` = (`21 years` + `22 to 24 years` + `25 to 29 years`),
      `30 to 39` = (`30 to 34 years` + `35 to 39 years`),
      `40 to 49` = (`40 to 44 years` + `45 to 49 years`),
      `50 to 59` = (`50 to 54 years` + `55 to 59 years`),
      `60 and over` = (`60 and 61 years` + `62 to 64 years` + `65 and 66 years` + `67 to 69 years` + `70 to 74 years` + `75 to 79 years` + `80 to 84 years` + `85 years and over`)
         ) %>% 
   select(metro_area, sex, `20 to 29`, `30 to 39`, `40 to 49`, `50 to 59`, `60 and over`) 
```



```{r}
#pivoting
females <- females %>% 
   pivot_longer(cols = colnames(females)[3:7], names_to = 'age', values_to = 'estimate')
```

```{r}
#combine male and females into single object
sex_by_age <- bind_rows(males, females)
```


```{r}
#save as csv file
write_csv(sex_by_age, 'data/sex_by_age.csv')
```









