---
title: "R Notebook people3 alg"
author: "Armelle Le Guelte"
date: "12/09/2020"
output: html_notebook
--- 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load the censusapi library
library(censusapi)

# Load other data-cleaning libraries
library(tidyr)
library(stringr)
library(dplyr)

# Create a new dataframe with the full list of available census APIs
apis <- listCensusApis()

# Take a look at the available APIs
# View(apis)
```

#From Taylor for acs1 sex, age and race for acs1 2019

```{r}
acs1vars <- listCensusMetadata(
    name = "acs/acs1", 
    type = "variables",
    vintage = 2019)
```

```{r}
acs1 <- getCensus(
   name = "acs/acs1",
   vintage = 2019,
   vars = 'group(B02001)',
   region = 'county:*',
   regionin = 'state: 47')
```


```{r}
#getting all column names from acs1
acs1_column_names <- colnames(acs1)

#getting selected columns to match with metadata
selected_acs1_column_names <- acs1_column_names[3:42]

#matching names and labels 
metadata_name_label_match <- acs1vars %>%
   filter(name %in% selected_acs1_column_names) %>%
   select(label) %>%
   pull() #creates vector

#naming the elements of the vector
names(metadata_name_label_match) <- acs1vars %>%
   filter(name %in% selected_acs1_column_names) %>%
   select(name) %>%
   pull() 

#assigning column names
colnames(acs1) <- c(colnames(acs1)[1:2], metadata_name_label_match[acs1_column_names[3:42]], colnames(acs1)[43:44])

#reassigning cleaned acs1
cleaned_acs1 <- acs1 %>% 
   select(colnames(acs1)[!is.na(colnames(acs1))]) 
```

```{r}
#save as a csv file
write.csv(cleaned_acs1, "data/acs_1y_2019.csv", row.names = FALSE)
```

### Test on asc5 data 2018

```{r}

# Create a new dataframe to store the metadata for the 2018 ACS 5-year dataset
acs5vars <- listCensusMetadata(
 name = "acs/acs5",
 vintage = 2018,
 type = "variables"
)

head(acs5_2018)

```
```{r}
#Get age, sex and race
#Estimate 2014-2018

acs5 <- getCensus( 
                  name = "acs/acs5",   
                  vintage = 2018, 
                  vars = "group(B02001)",
                  region = 'county:037',
                  regionin = 'state: 47')
head(acs5_2018_race)
```

```{r}
#getting all column names from acs5
acs5_column_names <- colnames(acs5)

#getting selected columns to match with metadata
selected_acs5_column_names <- acs5_column_names[4:20]

#matching names and labels 
metadata_name_label_match <- acs5vars %>%
   filter(name %in% selected_acs5_column_names) %>%
   select(label) %>%
   pull() #creates vector

#naming the elements of the vector
names(metadata_name_label_match) <- acs5vars %>%
   filter(name %in% selected_acs5_column_names) %>%
   select(name) %>%
   pull() 

#assigning column names
colnames(acs5) <- c(colnames(acs5)[1:3], metadata_name_label_match[acs5_column_names[4:20]],colnames(acs5)[21:44])

#reassigning cleaned acs5
cleaned_acs5 <- acs5 %>% 
   select(colnames(acs5)[!is.na(colnames(acs5))]) 

```



##### 2018 ACS 5 year data profile because less variables but get what I need

```{r}

# Create a new dataframe to store the metadata for the 2018 ACS 5-year dataset
acs5_vars <- listCensusMetadata(
 name = "acs/acs5/profile",
 vintage = "2018",
 type = "variables"
)
```


```{r}
# Count the number of times '!!' shows up as a separator in the `label` field
max(str_count(acs5_vars$label, "!!"))

#nb it shows 7 times so I will need to make 8 columns

# Split the 'label' columns into 8 columns and keep the 'label' column
acs5_vars <- acs5_vars %>%
     separate(
     label,
     c('label1', 'label2', 'label3', 'label4', 'label5', 'label6', 'label7', 'label8'),
     sep = "!!",
     remove = FALSE,
     convert = FALSE
     )
```

##### Decide what to keep in the ACS 2018 5-year data

```{r}
# label2 has what I'm looking for (age, race, ethnicity, sex and education)
acs5_label2 <- unique(acs5_vars$label2)
View(acs5_label2)
```


```{r}
# Create a list of the label_02 values we want to filter on
label2_vars_interest <- c('ANCESTRY',
'RACE',
'EDUCATIONAL ATTAINMENT',
'SEX AND AGE'
)

# Create a new dataframe with the variables we want
ppl3_acs5_vars <- acs5_vars %>% 
        filter(label2 %in% label2_vars_interest)
```

##### Get the data for Davidson County, TN
NB: TN = state:47 and davidson = county:037

```{r}
# Make a list of ppl3_acs5_vars table
ppl3_names_list <- ppl3_acs5_vars$name
View(ppl3_names_list)

# Get acs5 from censusapi
acs5_data <- getCensus(
        name = "acs/acs5/profile",
        vintage = "2018",
        region = "county:037",
        regionin = "state:47",
        vars = ppl3_names_list
)

```

```{r}
# Pivot the dataframe so there aren't hundreds of columns
acs5_data <- pivot_longer(
        acs5_data,
        cols = starts_with("DP"),
        names_to = "name",
        values_to = "value"
)
```

```{r}
# Join acs5_data to the variables from metadata to get all of the labels information
acs5_data <-
        inner_join(acs5_data, ppl3_acs5_vars, by = "name", copy = FALSE)
```

```{r}
# Save it as a csv file
write.csv(acs5_data, "data/acs_5y_2018_data.csv", row.names = FALSE)
```

### How to delete columns using dplyr

select(Your_Dataframe, -c(X, Y)
